---
# title           : provision.yml
# description     : Main provision
# author		      : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2020-07-17
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6


- name: provision manjaro/i3 workstation
  hosts: manjaro
  connection: local

  vars:
    wallpaper_dir: "{{ playbook_dir }}/roles/base/files/wallpapers"
    desktop_wallpaper: "3508x2480-alien-vs-predator.png"

  roles:
    - base
    # - development

...
