---
# title           : docker.yml
# description     : Task manifest for provision docker
# author          : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6

- name: Install docker packages
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present
  become: true
  tags:
    - packages
    - docker

- name: Enable docker service
  systemd:
    name: docker
    state: started
    enabled: true
  become: true
  tags:
    - docker

- name: Add user to docker group
  user:
    name: "{{host_username}}"
    groups: docker
    append: true
  become: true
  tags:
    - docker
