---
# title           : main.yml
# description     : Main task manifest for development role
# author          : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6

- name: Install Development Packages
  include_tasks: packages.yml
  tags:
    - packages

- name: Install and Setup Emacs
  include_tasks: emacs.yml
  tags:
    - packages
    - update
    - emacs
    - spacemacs

- name: Install and Setup Docker, Docker Compose
  include_tasks: docker.yml
  tags:
    - packages
    - docker

- name: Install and Setup NVM, Node, and NPM
  include_tasks: nvm.yml
  tags:
    - nvm
    - update
