---
# title           : php.yml
# description     : Task manifest for provisioning php
# author          : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6

- name: Install composer
  ansible.builtin.shell: |
    cd /home/{{ host_username }}
    source /home/{{ host_username }}/.zshrc
    /usr/bin/wget https://raw.githubusercontent.com/composer/getcomposer.org/95d11ed947f602b5a5f83f80c062e134d62c9f4b/web/installer -O - -q | php -- --quiet
    mv composer.phar /usr/bin/composer
    composer global require "squizlabs/php_codesniffer=*"
    mkdir /home/{{ host_username }}/.rulesets
    cd /home/{{ host_username }}/.rulesets
    git clone -b master https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
    git clone git@github.com:PHPCompatibility/PHPCompatibility.git compatibility
    git clone git@github.com:PHPCSStandards/PHPCSUtils.git utils
    phpcs --config-set installed_paths $PWD/wpcs,$PWD/utils,$PWD/compatibility
  args:
    executable: /usr/bin/zsh
  become: true
  tags:
    - php
...
