---
# title           : python.yml
# description     : Task manifest for provisioning python
# author          : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6

- name: Install python packages
  community.general.pacman:
    name:
      - python-poetry
      - pyenv
    state: present
  become: true
  tags:
    - python
    - packages

- name: Add poetry autocomplete
  ansible.builtin.shell: |
    source ~/.zshrc
    mkdir $ZSH_CUSTOM/plugins/poetry
    poetry completions zsh > $ZSH_CUSTOM/plugins/poetry/_poetry
  args:
    executable: /usr/bin/zsh
  tags:
    - python
    - poetry

- name: Add pyenv global python version
  ansible.builtin.shell: |
    source ~/.zshrc
    pyenv install 3.9.6
    pyenv global 3.9.6
  args:
    executable: /usr/bin/zsh
  tags:
    - python
    - pyenv
...
