---
# title           : git.yml
# description     : Task manifest for provisioning git
# author          : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6


- name: Symlink git config file
  file:
    state: link
    force: true
    owner: "{{ host_username }}"
    group: "{{ host_username }}"
    src: "{{ role_path }}/files/git/gitconfig"
    dest: $HOME/.gitconfig
