---
# title           : i3.yml
# description     : Task manifest for provisioning i3wm
# author          : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6


- name: Symlink i3wm config file
  file: &symlink_options
    state: link
    force: true
    owner: "{{ host_username }}"
    group: "{{ host_username }}"
    src: "{{ role_path }}/files/i3/config"
    dest: $HOME/.i3/config

- name: Set wallpaper via nitrogen
  ansible.builtin.command:
    argv:
      - /usr/bin/nitrogen
      - "--set-centered"
      - "{{ wallpaper_dir }}/{{ desktop_wallpaper }}"

- name: Create screenshot directory
  ansible.builtin.file:
    path: $HOME/Pictures/Screenshots
    state: directory
    mode: '0755'

- name: Symlink zone info
  file:
    <<: *symlink_options
    src: "{{ role_path }}/files/zoneinfo/Asia/Manila"
    dest: /usr/share/zoneinfo/Asia/Manila
  become: true

