---
# title           : main.yml
# description     : Main task manifest base role
# author		      : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6


#===============================================================================
# Setup zsh + oh-my-zsh
#===============================================================================
- name: Re/De/Install Packages
  include_tasks: packages.yml

- name: Configure ZSH
  include_tasks: zsh.yml

- name: Configure X
  include_tasks: x.yml

- name: Configure P10k
  include_tasks: p10k.yml

- name: Configure rofi
  include_tasks: rofi.yml
...
