---
# title           : zsh.yml
# description     : Task manifest for provision zsh
# author		      : Jerven Clark Chua
# email           : jervenclark@gmail.com
# date created    : 2021-03-09
# date modified   : 2021-03-09
# version         : 0.0.1
# ansible_version : 2.10.6


#===============================================================================
# Setup zsh + oh-my-zsh
#===============================================================================
- name: change user shell to zsh
  become: yes
  user:
    name: "{{ host_username }}"
    shell: /usr/bin/zsh

- name: Check if omz directory exists
  stat:
    path: $HOME/.ohmyzsh
  register: omz_dir

- name: Clone oh-my-zsh
  git:
    repo: git@github.com:ohmyzsh/ohmyzsh.git
    version: master
    dest: $HOME/.ohmyzsh
    accept_hostkey: true
  when: ! omz_dir.stat.exists != true

- name: Symlink zsh config
  file: &symlink_options
    state: link
    force: true
    owner: "{{ host_username }}"
    group: "{{ host_username }}"
    src: "{{ role_path }}/files/zshrc"
    dest: $HOME/.zshrc

- name: Check if omz-autosuggestions directory exists
  stat:
    path: $HOME/.ohmyzsh/custom/plugins/zsh-autosuggestions
  register: omz_dir

- name: Clone omz-autosuggestions
  git:
    repo: git@github.com:zsh-users/zsh-autosuggestions.git
    version: master
    dest: $HOME/.ohmyzsh/custom/plugins/zsh-autosuggestions
    accept_hostkey: true
  when: ! omz_dir.stat.exists != true


- name: Symlink zsh custom scritps
  file:
    <<: *symlink_options
    src: "{{ role_path }}/files/zsh"
    dest: $HOME/.ohmyzsh/custom/plugins/jech



#===============================================================================
# Setup Fonts
#===============================================================================
- name: Symlink fonts directory
  file:
    <<: *symlink_options
    src: "{{ role_path }}/files/fonts/MesloLGS NF"
    dest: "/home/{{ host_username }}/.fonts"
  become: true

- name: Clear font cache
  ansible.builtin.shell: fc-cache -fv

...
